version: "3.9"

services:
  firestore:
    build:
      context: ./firestore
    image: backpod/firestore
    networks:
      - backpod-network
    ports:
      - "8080:80"
  web:
    build:
      context: ./web
    image: backpod/web
    ports:
      - "8888:80"
    env_file:
      - ".env.web"
    volumes:
      - "./web:/app"
    networks:
      - backpod-network

networks:
  backpod-network:
